- api/src/main/resources/moduleApplicationContext.xml
Updates to use newer PropertySourcesPlaceholderConfigurer bean rather
than old-style property-placeholder.
Skipped this as currently this behavior is not used anywhere. 
Skipped this step as XML is not reformatted; this keeps the PR …
> FM2-19: SAXParseException on Platform 2.1.4

- api/src/main/java/org/openmrs/module/fhir2/api/FhirLocationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirLocationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/LocationTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProvider.java
Added the endpoint to get location by uuid. The Location resource currently has only three properties id, name and description.
see https://issues.openmrs.org/browse/FM2-12
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code …
> Location resource implementation

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirGlobalPropertyService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirGlobalPropertyDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/TelecomTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TelecomTranslatorImpl.java
- api/src/main/resources/fhir.properties
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TelecomTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImplTest_initial_data.xml
- omod/src/main/resources/config.xml
Implemented telecom translator
see https://issues.openmrs.org/browse/FM2-20
> FM2-20: Added telecom translator

- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImplTest.java
Added patientServiceImpl tests
> Improve test coverage

- api/src/main/java/org/openmrs/module/fhir2/Task.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirTaskService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirTaskDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/TaskTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImpl.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProvider.java
Implement a representation of the FHIR task resource for OpenMRS that's sufficient to support a test order communication workflow (https://www.hl7.org/fhir/workflow-communications.html#12.6.2.1).
see https://issues.openmrs.org/browse/FM2-2
No? -> figure out why and add the fix to …
> FM2-2: Implement the Task Resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirGlobalPropertyService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirGlobalPropertyDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TelecomTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonNameTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TelecomTranslatorImplTest.java
> Fixed mvn clean install formatting issues

- .vscode/settings.json
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/LocationAddressTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationAddressTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationAddressTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
see https://issues.openmrs.org/browse/FM2-12
> FM2-12 : Location resource address property definition

- README.md
> Updated travis and codecov badge Link

- omod/src/main/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/util/MethodOutComeUtils.java
> Fixed servletException task resource @Update @Create

- api/src/main/resources/liquibase.xml
> Fixed failing liquibase for task resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirLocationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirLocationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProvider.java
Added ability to search a location using location name
see https://issues.openmrs.org/browse/FM2-24
> Added search by name for location resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConceptSource.java
- api/src/main/java/org/openmrs/module/fhir2/FhirTestConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirConceptService.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirConceptSourceService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirConceptDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirConceptSourceDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConceptDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConceptSourceDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConceptServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConceptSourceServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ConceptTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImpl.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirConceptDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirConceptSourceDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConceptServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConceptSourceServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirConceptDaoImplTest_initial_data.xml
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirConceptSourceDaoImplTest_initial_data.xml
Adds a translator and required metadata to turn OpenMRS concepts to CodeableConcepts
see https://issues.openmrs.org/browse/FM2-21 …
> FM2-21: Map Concepts to CodeableConcepts

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPersonService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPersonServiceImpl.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PersonFhirResourceProvider.java
Adds search by name features by making the birthdate parameter on the `findSimilarPeople()` method optional.
see https://issues.openmrs.org/browse/FM2-26
No? Unsure? -> …
> FM2-26: Implement search by name for Person Resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirTaskService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProvider.java
Implement CREATE and UPDATE functionality for the FHIR Task resource.
see https://issues.openmrs.org/browse/FM2-2 …
> FM2-2 Task Resource CREATE and UPDATE implementation work

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPractitionerService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirPractitionerDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/PractitionerFhirResourceProvider.java
Added ability to search practitioner by name
see https://issues.openmrs.org/browse/FM2-27
> FM2-27: Implemented search by name

- api/src/main/resources/liquibase.xml
Fixed liquibase errors
see https://issues.openmrs.org/browse/FM2-28
> FM2-28: Fixed liquibase errors

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPractitionerService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirPractitionerDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PractitionerFhirResourceProvider.java
Added the ability to search practitioners by identifier
see https://issues.openmrs.org/browse/FM2-29
> FM2-29: Implemented search practitioners by identifier

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- omod/src/main/java/org/openmrs/module/fhir2/web/servlet/FhirRestServlet.java
- omod/src/main/resources/config.xml
https://issues.openmrs.org/browse/FM2-23
> FM2-23: Add paging provider

- api/src/main/java/org/openmrs/module/fhir2/api/FhirTaskService.java
- api/src/main/resources/liquibase.xml
Fixes the Create method for Task so a new Task is created
see https://issues.openmrs.org/browse/FM2-35
> FM2-35 Fix the Create method for Task

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/LocationTelecomTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTelecomTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTelecomTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImplTest_initial_data.xml
- omod/src/main/resources/config.xml
Location telecom translation implementation
see https://issues.openmrs.org/browse/FM2-31
> Location telecom translator implementation

- api/src/main/java/org/openmrs/module/fhir2/FhirException.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirServiceRequestService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirServiceRequestDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirServiceRequestDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirServiceRequestServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ServiceRequestTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirServiceRequestDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirServiceRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirServiceRequestTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/ServiceRequestFhirResourceProvider.java
Basic implementation of the ServiceRequest resource with simple mappings from Order.Active to ServiceRequest.Status.
see https://issues.openmrs.org/browse/FM2-6
No? …
> FM2-6 Implement the ServiceRequest Resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirLocationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirLocationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProvider.java
Added endpoints to find location by address properties. City, Country, Postal code and State.
see https://issues.openmrs.org/browse/FM2-37
No? Unsure? -> execute command …
> Find location by city, country, state and postal code

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
> Declare all constants final

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TelecomTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TelecomTranslatorImplTest.java
- omod/src/main/resources/config.xml
Added telecom property to practitioner
see https://issues.openmrs.org/browse/FM2-41
> FM2-41: Added telecom property to practitioner resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirEncounterService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirEncounterDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/EncounterTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/FhirReferenceUtils.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/util/FhirReferenceUtilsTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProvider.java
Initial work on encounter resource.
Properties implemented:
- Id
- status
- Subject: (patient)
see https://issues.openmrs.org/projects/FM2/issues/FM2-10
No? Unsure? -> …
> FM2-10: Initial implementation for encounter resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirTaskService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConceptServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConceptSourceServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPersonServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirServiceRequestServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImpl.java
Added @Transactional annotation to all service Implementation methods
see https://issues.openmrs.org/browse/FM2-46 …
> FM2-46: Added @Transactional to all serviceImpl methods

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/EncounterParticipantTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterParticipantTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/FhirReferenceUtils.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterParticipantTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/util/FhirReferenceUtilsTest.java
Added participant property
see https://issues.openmrs.org/browse/FM2-43
> FM2-43: Added participant property to encounter resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirObservationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirObservationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationComponentTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationStatusTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationValueTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationComponentTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationStatusTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationValueTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationComponentTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationStatusTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationValueTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/ObservationFhirResourceProvider.java
This is the initial implementation of the Observation Resource, supporting getting the Observation by UUID.
see https://issues.openmrs.org/browse/FM2-11
No? Unsure? -> …
> FM2-11 Implement the Observation Resource

- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
Small infrastructure change to add the [Maven wrapper script](https://github.com/takari/maven-wrapper) to the project. This should allow people to get this module up and running a bit quicker (i.e., it can be compiled without explicitly installing Maven; installing Maven is still necessary to use the SDK).
Not tracked in JIRA.
added all formatting …
> Add the Maven Wrapper to the project

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/EncounterLocationTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterLocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/FhirReferenceUtils.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterLocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/util/FhirReferenceUtilsTest.java
Added location property
see https://issues.openmrs.org/browse/FM2-42
> FM2-42: Added location property to encounter resource

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirServiceRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImplTest.java
Added support for providing `ServiceRequest.code` for FM2-6
see https://issues.openmrs.org/browse/FM2-6
> FM2-6 Support for ServiceRequest.code

- api/src/main/java/org/openmrs/module/fhir2/api/FhirEncounterService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirEncounterDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderTest.java
Added ability to search all ecounters of a patient by identifier
see https://issues.openmrs.org/browse/FM2-50 …
> FM2-50: Added search encounters by PatientIdentifier

- api/src/main/java/org/openmrs/module/fhir2/api/FhirObservationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirObservationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImplTest_initial_data_suppl.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/ObservationFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ObservationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ObservationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/servlet/BaseFhirResourceProviderTest.java
Enables Observations to be searched by ConceptSource and Code. Also enables search by Patient and Encounter and allows sorting of all queries.
see https://issues.openmrs.org/browse/FM2-45
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure …
> FM2-45 Enable Observations to be searched by ConceptSource and Code

- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderWebTest.java
Added web tests for encounter resource provider
untracked
> Added web tests for Encounter resource provider

- omod/src/test/java/org/openmrs/module/fhir2/providers/PractitionerFhirResourceProviderWebTest.java
Added web tests for practitioner resource provider
untracked
> Added web tests for practitioner resource provider

- api-2.0/pom.xml
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/dao/Impl/FhirConditionDaoImpl_2_0.java
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_0.java
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/translators/ConditionClinicalStatusTranslator.java
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionClinicalStatusTranslatorImpl_2_0.java
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/dao/Impl/FhirConditionDaoImpl_2_0Test.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_0Test.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionClinicalStatusTranslatorImpl_2_0Test.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirConditionService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirConditionDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ConditionTranslator.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProvider.java
- omod/src/main/resources/config.xml
- omod/src/test/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProviderWebTest.java
- pom.xml
- Initial condition resource implementation
- Initial crafting, multiple support for different openmrs versions
see https://issues.openmrs.org/browse/FM2-51
No? Unsure? -> …
> FM2-51: Initial Implementation of condition resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
Created translations between OpenMrs location tags and FHIR tags 
see https://issues.openmrs.org/browse/FM2-32 …
> FM2-32 : Created translations for location tags

- api/src/main/java/org/openmrs/module/fhir2/api/FhirLocationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirLocationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProviderWebTest.java
I added the feature to search for locations using location tags
see https://issues.openmrs.org/browse/FM2-33 …
> FM2-33 : Added ability to search locations using location tags

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirDiagnosticReportService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirDiagnosticReportDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirDiagnosticReportDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/DiagnosticReportTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationReferenceTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AbstractReferenceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/DiagnosticReportTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirDiagnosticReportDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/DiagnosticReportTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirDiagnosticReportDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProviderWebTest.java
This PR adds a simple implementation of the [DiagnosticReport](https://www.hl7.org/fhir/diagnosticreport.html) FHIR resource that does not yet support the result element. 
see https://issues.openmrs.org/browse/FM2-5
No? -> figure out why and add the fix to your commit. It is your …
> Added basic support for the DiagnosticReport FHIR resource for FM2-5

- api-2.0/pom.xml
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/dao/Impl/FhirConditionDaoImpl_2_0.java
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_0.java
- omod/pom.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProvider.java
- pom.xml
* Remove unnecessary dependencies
untracked
> Make Condition Resource deployable to openmrs platform  at least version 2.0.5

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
…rties
Added support for Location.partOf and translations for unmapped properties
see https://issues.openmrs.org/browse/FM2-58 …
> FM2-58 Added support for Location.partOf and translations for unmapped properties

- api-2.2/pom.xml
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/dao/Impl/FhirConditionDaoImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/TestFhirSpringConfiguration.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/dao/Impl/FhirConditionDaoImpl_2_2Test.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2Test.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2Test.java
- omod/pom.xml
- omod/src/main/resources/config.xml
- pom.xml
Added condition resource implementation
Only Id and Subject translated for now
see https://issues.openmrs.org/browse/FM2-51 …
> FM2-51: Condition resource implementation for openmrs platform at least version 2.2.0

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionVerificationStatusTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2Test.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionVerificationStatusTranslatorImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ConditionVerificationStatusTranslator.java
Added verificationStatus translator
see https://issues.openmrs.org/browse/FM2-66
> FM2-66: Added verificationStatus translator for openmrs platform v2.2.0

- api-2.1/pom.xml
- api-2.1/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationInterpretationTranslatorImpl_2_1.java
- api-2.1/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationStatusTranslatorImpl_2_1.java
- api-2.1/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationInterpretationTranslatorImpl_2_1Test.java
- api-2.1/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationStatusTranslatorImpl_2_1Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationInterpretationTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationInterpretationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationInterpretationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
- omod/pom.xml
- omod/src/main/resources/config.xml
- pom.xml
I added a mapping for Observation.interpretation and Observation.status for 2.1.0 and newer 
see https://issues.openmrs.org/browse/FM2-53
No? Unsure? -> execute command …
> Added mappings for Observation.interpretation and Observation.status for 2.1.0 and newer

- api-2.0/pom.xml
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/CreatorReferenceTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AbstractReferenceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/CreatorReferenceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AbstractReferenceHandlingTranslatorTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/CreatorReferenceTranslatorImplTest.java
Added missing properties
-  Recorder
- RecorderDate
- Code (condition coded/ condition non coded)
- OnsetDateTime
see https://issues.openmrs.org/browse/FM2-69
No? Unsure? …
> FM2-69: Added missing properties for condition resource

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionVerificationStatusTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionVerificationStatusTranslatorImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
verification status
see https://issues.openmrs.org/browse/FM2-66
> FM2-66: Mapped verificationstatus to valueset

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
Added support for telecom to Patient
see https://issues.openmrs.org/browse/FM2-65
> FM2-65 Add support for telecom to Patient

- api/src/main/java/org/openmrs/module/fhir2/api/FhirUserService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirUserDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirUserDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirUserServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/CreatorReferenceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirUserDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirUserServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/CreatorReferenceTranslatorImplTest.java
Added fhir user service
Untracked
> Added FhirUserService

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPatientService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirPatientDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/servlet/BaseFhirResourceProviderTest.java
[FHIR Search](https://www.hl7.org/fhir/search.html) provides rather complex ways of querying the database. This is where we start to need the Dao infrastructure we've been building into the module: to not only interact with the OpenMRS API, but to provide us a way to answer FHIR searches as efficiently as possible.
[Hibernate's CriteriaQuery](https://docs.jboss.org/hibernate/orm/4.3/manual/en-US/html_single/#querycriteria) API gives us the flexibility to dynamically add conditions to create a full query, which is useful for doing this kind of translation work.
The purpose of this draft PR is to show a vision for what this might look like and get some feedback from our active developers (or anyone else in the community who is interested). Please take a look, especially at this branches …
> Improve ability to generate complex queries

- pom.xml
Updated the module to use HAPI FHIR 4.2.0
With the release of FHIR [4.1.0 and 4.2.0](https://build.fhir.org/history.html) many new resources have been added. Among this is the [ObservationDefinition](https://build.fhir.org/observationdefinition.html) resource. This is specifically used to define a set of  constraints applicable to the value produced by observations of this kind. Openmrs currently enforces some of this constraints with the use of concept classes and concept sets...
Other updates did not touch the resources that have currently been worked on here. I also tested all the resources to ensure there were no silent failures.
see https://issues.openmrs.org/browse/FM2-39
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits …
> FM2-39 : Updated the module to use HAPI FHIR 4.2.0

- api-2.0/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/PractitionerReferenceTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/PractitionerTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AbstractReferenceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterParticipantTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerReferenceTranslatorProviderImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerReferenceTranslatorUserImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AbstractReferenceHandlingTranslatorTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerReferenceTranslatorProviderImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerReferenceTranslatorUserImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImplTest.java
Map openmrs user to practitioner
Properties added;
- Practioner.id
-  Practitioner.identifier
- Practitioner.name
- Practitioner.address
- Practitioner.gender
- Practitioner.birthdate
see https://issues.openmrs.org/browse/FM2-71
No? -> figure out why and add the fix to your …
> FM2-71: Create mapping from openmrs user to practitioner

- api-2.1/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationInterpretationTranslatorImpl_2_1.java
- api-2.1/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationStatusTranslatorImpl_2_1.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionClinicalStatusTranslatorImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionVerificationStatusTranslatorImpl_2_2.java
- omod/src/main/resources/config.xml
Updated version handling to work on platform 2.4.0 and newer in the 2.x series
see https://issues.openmrs.org/browse/FM2-77 …
> FM2-77 Add support for platform 2.4.0 and newer

- api-2.2/pom.xml
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2Test.java
Added missing properties for condition resource : openmrs platform version 2.2.* - 2.3.* implementation
see https://issues.openmrs.org/browse/FM2-69
No? Unsure? -> execute …
> FM2-69: Added missing props for condition openmrs platform v2.2 - v2.3

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirAllergyIntoleranceService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirAllergyIntoleranceDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/AllergyIntoleranceTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderWebTest.java
Allergy resource initial implementation
More description on the ticket . 
see https://issues.openmrs.org/browse/FM2-82 …
> FM2-82 : Allergy resource initial implementation

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
Currently, observations of a group are returned as individual components, this PR aims to return these observations as **hasMember** fields instead.
see https://issues.openmrs.org/browse/FM2-76
No? -> figure out why and add the fix to your commit. It is your responsibility to make …
> FM2-76: Implement Observation.hasMember

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/FhirTestConstants.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
Additional properties to allergyIntolerance resource. The added properties includes **patient, recorder, recorderDate, lastOccurrence**
see https://issues.openmrs.org/browse/FM2-84
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your …
> FM2-84 : Additional properties to allergyIntolerance resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationReferenceRangeTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
see https://issues.openmrs.org/browse/FM2-61
> FM2-61 Add support for Observation.referenceRange

- api-2.0/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/DiagnosticReportTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/DiagnosticReportTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/FhirTaskTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImplTest.java
Populate lastUpdated for all resources
see https://issues.openmrs.org/browse/FM2-85
> FM2-85 : Populate lastUpdated for all resources

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImplTest.java
Fixed tests for Observation
see https://issues.openmrs.org/browse/FM2-89
> FM2-89 Fix tests for Observation

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirGlobalPropertyService.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
see https://issues.openmrs.org/browse/FM2-84
> FM2-84 : Additional properties to allergyIntolerance resource post-commit

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseServiceRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonNameTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImpl.java
Remove incorrect checks
see https://issues.openmrs.org/browse/FM2-86
>  FM2-86: Audit codebase for incorrect checks of resource presence

- api/src/main/java/org/openmrs/module/fhir2/api/FhirEncounterService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirEncounterDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderWebTest.java
FM2-79 Improved Search for Encounter
see https://issues.openmrs.org/browse/FM2-79
> FM2-79 Improve Search for Encounter

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPersonService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirPersonDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPersonServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPersonServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PersonFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/PersonFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/PersonFhirResourceProviderWebTest.java
* Model `FhirPersonResourceProvider`  to provide search  by name, gender, birth date, address.
* Added tests for the Provider class
Todo:
see https://issues.openmrs.org/browse/FM2-81
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your …
> FM2-81: Improving Search for Person Resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/PatientTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ToFhirProvenance.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AbstractProvenanceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/FhirUtils.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AbstractProvenanceHandlingTranslatorTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/servlet/BaseFhirProvenanceResourceTest.java
Added audit info to provenance resource for patient resource
see https://issues.openmrs.org/browse/FM2-72 …
> FM2-72: Map OpenMRS Object Audit values to Provenance Resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPatientService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirPatientDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProviderWebTest.java
Add ability to search patients using address-country
see https://issues.openmrs.org/browse/FM2-90
> FM2-90 : Add ability to search patients using address-country

- omod/src/main/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/ObservationFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PatientFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PersonFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/PractitionerFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/util/FhirServerUtils.java
In the last PR #92, I introduce `FhirUtils.java` at the API sub-module. So the file name is conflicting with another file in Omod. I have renamed the one in Omod to `FhirServerUtils.java`
Untracked
No? -> figure out why and add the fix to your commit. It is your responsibility to …
> Rename FhirUtils to FhirServerUtils @Omod sub-module

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirMedicationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderWebTest.java
FHIR Medication Resource Initial Implementation
see https://issues.openmrs.org/browse/FM2-98
> FM-98 : FHIR Medication Resource Initial Implementation

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
Remove patient service from encounter translator
see https://issues.openmrs.org/projects/FM2/issues/FM2-97 …
> FM2-97: Remove openmrs patient service from encounter translator

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImplTest.java
Remove openmrs services in favour of Criteria API
Untracked
> Remove openmrs services in favour of Hibernate criteria API

- api-2.0/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_0Test.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProvider.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderWebTest.java
Part III 
Added provenance for condition, AllergyIntolerance & Encounter
see https://issues.openmrs.org/browse/FM2-72 …
> FM2-72: Added provenances for additional resources

- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ServiceRequestFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/servlet/BaseFhirResourceProviderTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/TestDiagnosticReport_CreateUpdate.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/TestDiagnosticReport_CreateUpdate_NoId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/TestDiagnosticReport_CreateUpdate_WrongId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/TestTask_CreateUpdate.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/TestTask_CreateUpdate_NoId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/TestTask_CreateUpdate_WrongId.json
FM2-40 Implement OMOD unit tests for Task, Service Request, and Diagnostic Report
Added OMOD unit tests for Task, DiagnosticReport, and ServiceRequest
see https://issues.openmrs.org/browse/FM2-40
No? -> figure out why and add the fix to your commit. It is your responsibility to …
>  FM2-40 Implement OMOD unit tests for Task, Service Request, and Diagnostic Report

- api/src/main/java/org/openmrs/module/fhir2/api/translators/CustomizableMetadataTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/CustomizableMetadataTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/CustomizableMetadataTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImplTest.java
Added customizableMetadata Translator to handle openmrs object that extends BaseCustomizableMetadata. Location & Provider
see https://issues.openmrs.org/browse/FM2-102
No? …
> FM2-102: Implement customizableMetadata Translator

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/FhirReference.java
- api/src/main/java/org/openmrs/module/fhir2/FhirTask.java
- api/src/main/java/org/openmrs/module/fhir2/FhirTaskInput.java
- api/src/main/java/org/openmrs/module/fhir2/FhirTaskOutput.java
- api/src/main/java/org/openmrs/module/fhir2/FhirTaskParam.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirTaskService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirTaskDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ReferenceTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseServiceRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ReferenceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImpl.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/DiagnosticReportTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/FhirTaskTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ReferenceTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest_initial_data.xml
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest_owner_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/TaskFhirResourceProviderWebTest.java
Implemented support for elements required for the Lab workflow in Task, DiagnosticReport, and ServiceRequest.
see https://issues.openmrs.org/browse/FM2-75
No? Unsure? -> …
> FM2-75 Address gaps in supported elements for DiagnosticReport, Task, and ServiceRequest 

- api/src/main/java/org/openmrs/module/fhir2/api/FhirAllergyIntoleranceService.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirGlobalPropertyService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirAllergyIntoleranceDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirGlobalPropertyDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImplTest_initial_data.xml
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/servlet/BaseFhirResourceProviderTest.java
Implemented search by patient reference, allergy category, allergy substance, severity, manifestation/reaction and clinical status
see https://issues.openmrs.org/browse/FM2-83
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code …
> FM2-83 : Create appropriate search functionality for allergy intolerance resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImplTest.java
Additional properties to Medication resource
see https://issues.openmrs.org/browse/FM2-103
> FM2-103 : Implement additional properties for Medication resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirLocationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirLocationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProviderWebTest.java
1. Added a single search method for Location resource containing name, city, state, postal code, country, tags.
2. Implemented the "part of" functionality as well to the above.
3. Added sorting by name, city, country, postal code, state.
see https://issues.openmrs.org/browse/FM2-80
No? -> execute above …
> FM2-80: Improve Search for Location Resource

- api/src/main/java/org/openmrs/module/fhir2/FhirTask.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImpl.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImplTest.java
Fixing liquibase migration issues for FM2-106
see https://issues.openmrs.org/browse/FM2-106
>  FM2-106: Fix liquibase migration issues

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationRequestService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirMedicationRequestDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationReferenceTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationRequestPriorityTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationRequestStatusTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationRequestTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AbstractReferenceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationReferenceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestPriorityTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationReferenceTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestPriorityTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImpl_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/MedicationRequestFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationRequestFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationRequestFhirResourceProviderWebTest.java
Initial implementation of medication request resource
see https://issues.openmrs.org/browse/FM2-94
> FM2-94: Initial implementation of medicationRequest resource

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/CustomizableMetadataTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ProvenanceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/CustomizableMetadataTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ProvenanceTranslatorImplTest.java
Disable creating of provenance with update activity when dateChanged and changeBy are null.
see https://issues.openmrs.org/browse/FM2-108
No? Unsure? -> execute command …
> FM2-108: Shouldn't create update provenance if dateChanged&&changedBy==null

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirServiceRequestDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationBasedOnReferenceTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationEffectiveDatetimeTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AbstractReferenceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationBasedOnReferenceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationEffectiveDatetimeTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/CustomizableMetadataTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationBasedOnReferenceTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationEffectiveDatetimeTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ProvenanceTranslatorImplTest.java
Implemented additional fields for observations
> FM2-96: Implement additional fields for observations

- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirMedicationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderWebTest.java
see https://issues.openmrs.org/browse/FM2-105
> FM2-105 : Implement search functionality for medication resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirGlobalPropertyService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirGlobalPropertyDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirGlobalPropertyServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImplTest_initial_data.xml
I optimize database operations in allergy intolerance resource
see https://issues.openmrs.org/browse/FM2-113 …
> Optimize database operations in allergy intolerance resource

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/AbstractPersonDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImplTest_address_data.xml
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImplTest_initial_data.xml
see https://issues.openmrs.org/browse/FM2-95
> FM2-95: Implement sorting for Patient Resource

- api-2.0/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_0.java
- api-2.0/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_0.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_0Test.java
- api-2.0/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_0Test.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2Test.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2Test.java
- api-2.2/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImplTest_initial_data.xml
- api/src/main/java/org/openmrs/module/fhir2/api/FhirConditionService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirConditionDao.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ConditionResourceWebTest_create.json
Added support to create a new condition
see https://issues.openmrs.org/browse/FM2-70
> FM2-70: Added support to create condition

- api/src/main/java/org/openmrs/module/fhir2/api/translators/DosageTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/DosageTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/DosageTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImplTest.java
Added additional properties to medication request resource
* Note
* ReasonCode
* DosageInstruction
*  text
*  route
* asNeeded
see https://issues.openmrs.org/browse/FM2-114
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code …
> FM2-114: Added more additional properties to medication request resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirListService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirListDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirCohortListDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirCohortListServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ListTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirCohortListDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirCohortListServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirCohortListDaoImplTest_initial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/ListFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ListFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ListFhirResourceProviderWebTest.java
Created translations between cohort data model and Fhir ListResource for cohort properties in openmrs platform 2.0.5
see https://issues.openmrs.org/browse/FM2-115
No? …
> FM2-115: FHIR List Resource initial implementation

- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationAddressTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImplTest.java
Converted test assertion methods to assertThat() to improve code readability
see https://issues.openmrs.org/browse/FM2-117 …
> FM2-117 : Convert test assertion methods to assertThat() to improve code readability

- api-2.1/pom.xml
- api-2.1/src/main/java/org/openmrs/module/fhir2/api/translators/impl/CohortListEntryTranslatorImpl_2_1.java
- api-2.1/src/test/java/org/openmrs/module/fhir2/api/translators/impl/CohortListEntryTranslatorImpl_2_1Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirPatientDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ListEntryTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/CohortListEntryTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/CohortListEntryTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImplTest.java
Added support for Cohort.memberships in platform 2.1.0 and newer
see https://issues.openmrs.org/browse/FM2-116 …
> FM2-116 : Added support for Cohort.memberships in platform 2.1.0 and newer

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
Fixed Null pointer exception thrown when translating null encounter by returning null if openmrs encounter is null
see https://issues.openmrs.org/browse/FM2-123
No? …
> FM2-123: Fixed NPE thrown when trying to translate null encounter

- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirMedicationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/MedicationResourceWebTest_create.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/MedicationResourceWebTest_update.json
Implemented support for create and update for medication
see https://issues.openmrs.org/browse/FM2-118
> FM2-118 : Implement support for create medication

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/DiagnosticReportTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/DiagnosticReportTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
Reverted date created and date updated to read only
For openmrs objects this field are created dynamically  during creation and updating respectively.
For Fhir objects that will not be extending BaseOpenmrs objects it makes sense to populate this field to new Date() in the DAO layer during saving and updating. This will ensure that the fields are not saved as null when these they have not been provided in the payload
see https://issues.openmrs.org/browse/FM2-85
existing code that was well …
> FM2-85 : Revert date created and date updated to read only

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImpl.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/MedicationResourceWebTest_UdateWithWrongId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/MedicationResourceWebTest_UdateWithoutId.json
Improved test coverage on MedicationFhirResourceProvider update functionality
see https://issues.openmrs.org/browse/FM2-118 …
> FM2-118 : Improve test coverage on MedicationFhirResourceProvider update functionality

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDaoImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImplTest.java
When searching where there is no chain (e.g. `subject:Patient=...`) the value returned by `getChain()` is `null`. I've fixed this behaviour for a few cases and tests, though I can't claim this is comprehensive.
see https://issues.openmrs.org/browse/FM2-135
No? -> figure out why …
> FM2-135 Fix NPE when search by subject UUID

- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImplTest.java
> mvn formatting change

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirRelatedPersonService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirRelatedPersonDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirRelatedPersonDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirRelatedPersonServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/RelatedPersonTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/RelatedPersonTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/RelatedPersonDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirRelatedPersonServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/RelatedPersonTranslatorImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirRelatedPersonDaoImplTest_intial_data.xml
- omod/src/main/java/org/openmrs/module/fhir2/providers/RelatedPersonFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/RelatedPersonFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/RelatedPersonFhirResourceProviderWebTest.java
Initial implementation of Related person resource
see https://issues.openmrs.org/browse/FM2-133
> FM2-133: Initial implementation of related person resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationReferenceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationReferenceTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/servlet/BaseFhirResourceProviderTest.java
Implemented generic Dao classes to ensure code reuse in the Dao layer
see https://issues.openmrs.org/browse/FM2-143 …
> FM2-143 : Implement generic Dao classes to ensure code reuse in the Dao layer

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/RelatedPersonTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/RelatedPersonTranslatorImplTest.java
Added more mappings for Related person resource
-Patient reference
-Period - start & end
see https://issues.openmrs.org/browse/FM2-138
No? Unsure? -> execute command `git …
> FM2-138: Added patient and period mappings

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
Change adding of person link to use patient reference translator
see https://issues.openmrs.org/browse/FM2-141 …
> FM2-141: Refactored adding of person link to use patientReferenceTranslator

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImplTest.java
Fixed NPE thrown when trying to translate observation reference range with null `conceptNumeric.getLowNormal() `or `conceptNumeric.getHiNormal()`
see https://issues.openmrs.org/browse/FM2-142
No? -> figure out why and add the fix to your commit. It is your responsibility to make …
> FM2-142: Fixed NPE thrown when searching Observations by code

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2Test.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirConditionService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirConditionDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/CalendarFactory.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ConditionFhirResourceProviderTest.java
This PR implements the onset-age search parameter for the Condition resource. It converts all onset-age constraints into date constraints and apply them on `onsetDate`.
see https://issues.openmrs.org/browse/FM2-87
No? -> figure out why and add the fix to your commit. It is your …
> FM2-87: Add Condition onset-age search parameter

- api/src/main/java/org/openmrs/module/fhir2/api/FhirAllergyIntoleranceService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirAllergyIntoleranceDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/AllergyIntoleranceTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderWebTest.java
Updated Allergy DAO and Service to use generic methods.
see https://issues.openmrs.org/browse/FM2-147
> FM2-147 : Update Allergy DAO and Service

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- omod/src/main/java/org/openmrs/module/fhir2/web/servlet/FhirRestServlet.java
- omod/src/main/java/org/openmrs/module/fhir2/web/servlet/OpenmrsFhirAddressStrategy.java
- omod/src/main/resources/config.xml
@corneliouzbett Here's an implementation of an `IServerAddressStrategy` that solves (I think) the problem. It also adds a global property so you can tell it what it should use.
> Add custom strategy for determining URL

- api/src/main/java/org/openmrs/module/fhir2/api/FhirEncounterService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirEncounterDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterReferenceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterReferenceTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderWebTest.java
link;https://issues.openmrs.org/browse/FM2-152
> FM2-152: Update Encounter DAO and Service

- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationRequestService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirMedicationRequestDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationRequestTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationBasedOnReferenceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationBasedOnReferenceTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/MedicationRequestFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationRequestFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/MedicationRequestFhirResourceProviderWebTest.java
link:https://issues.openmrs.org/browse/FM2-154
> FM2-154: Update MedicationRequest Dao and service

- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationRequestTimingComponentTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationRequestTimingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTimingComponentTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTimingTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/DosageTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTimingComponentTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTimingTranslatorImplTest.java
Added additional properties
**Timing**
* event - DrugOrder.scheduledDate
* repeat.duration - DrugOrder.duration
* repeat.durationUnit - DrugOrder.durationUnits
* repeat.frequency - DrugOrder.frequency.frequencyPerDay if this is set, also set
* repeat.period - 1
* repeat.periodUnit - d
see https://issues.openmrs.org/browse/FM2-114
added all formatting …
> FM2-114:Added additional properties for medicationRequest resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirListService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirListDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirCohortListDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirCohortListServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ListTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirCohortListDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirCohortListServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/ListFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ListFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ListFhirResourceProviderWebTest.java
updated CohortList classes to use generic classes provided in the DAO and service layer
see https://issues.openmrs.org/browse/FM2-149
No? Unsure? -> execute command `git …
> FM2-149 : Update CohortList DAO and Service

- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
Updated medication DAO and service to use generic classes
see https://issues.openmrs.org/browse/FM2-171
> FM2-171 : Update medication DAO and service

- api/src/main/java/org/openmrs/module/fhir2/api/FhirDiagnosticReportService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirDiagnosticReportDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirDiagnosticReportDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/BaseFhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirDiagnosticReportDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/DiagnosticReportFhirResourceProviderWebTest.java
Updated DiagnosticReport resource with generic BaseFhirDao and BaseFhirService classes.
see https://issues.openmrs.org/browse/FM2-151
No? Unsure? -> execute command `git …
> FM2-151: Update DiagnosticReport DAO and Service

- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImplTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/AllergyIntoleranceFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/EncounterFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/ObservationFhirResourceProviderWebTest.java
Some provider web tests were missing for handling empty chained parameters and the corresponding getChain() asserts have been added as well.
see https://issues.openmrs.org/browse/FM2-175
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure …
> FM2-175: Correctly handled empty chained parameters

- api/src/main/java/org/openmrs/module/fhir2/api/FhirLocationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirLocationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterLocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterLocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/LocationFhirResourceProviderWebTest.java
Updated Location DAO and Service
see https://issues.openmrs.org/browse/FM2-153
> FM2-153: Update Location DAO and Service

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirObservationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/mappings/ObservationCategoryMap.java
- api/src/main/java/org/openmrs/module/fhir2/api/mappings/impl/BaseMapping.java
- api/src/main/java/org/openmrs/module/fhir2/api/mappings/impl/ObservationCategoryMapImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/SearchParameterMap.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationCategoryTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationCategoryTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProvider.java
- api/src/main/resources/observationCategoryMap.properties
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/ObservationSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderTest.java
- api/src/test/resources/observationCategoryMap.properties
- omod/src/test/java/org/openmrs/module/fhir2/providers/BaseFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/BaseFhirR3ResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/BaseFhirR4ResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderWebTest.java
This adds support for the `Observation.category` field in FHIR by determining the category from the concept class associated with the Observation, where this is possible.
see https://issues.openmrs.org/browse/FM2-182
> FM2-182: Add support for Observation.category

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderTest.java
LINK:https://issues.openmrs.org/browse/FM2-177
> FM2-177:Implement chaining for search on Location.partOf

- api/src/main/java/org/openmrs/module/fhir2/api/translators/AllergyIntoleranceSeverityTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceSeverityTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceSeverityTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderTest.java
Decongest AllergyIntoleranceTranslator by moving `AllergyIntolerance.AllergyIntoleranceSeverity` to its translator
see https://issues.openmrs.org/browse/FM2-188
> FM2-188:  Refactor AllergyIntolerance.AllergyIntoleranceSeverity to its own translator

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderTest.java
> Mvn formatting changes

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTimingComponentTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTimingComponentTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderTest.java
Fixed NPE thrown when duration and frequency are null
see https://issues.openmrs.org/browse/FM2-190
> FM2-190: Fix NPE thrown when drug order duration and frequency are null

- api/src/main/java/org/openmrs/module/fhir2/api/translators/AllergyIntoleranceCriticalityTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceCriticalityTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceCriticalityTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
Added AllergyIntolerance.AllergyIntoleranceCriticality property
see https://issues.openmrs.org/browse/FM2-187
> FM2-187: Add AllergyIntolerance.criticality property

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationRequestService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirMedicationRequestDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/MedicationRequestSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProviderTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImpl_initial_data.xml
FM2-209: Implement search for MedicationRequest Resource
issue: https://issues.openmrs.org/browse/FM2-209
It is still a work in progress and so I have made this initial PR to get some feedback before implementing in r4 as well as writing more tests. cc. @ibacher 
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure …
> FM2-209: Implement search for MedicationRequest Resource

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2Test.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirConditionService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirConditionDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/exceptions/FhirNotImplementedException.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ConditionFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ConditionFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/ConditionFhirR3ResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ConditionFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/ConditionFhirR3ResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ConditionFhirResourceProviderWebTest.java
Updated Condition Dao and Service to inherit generic methods
see https://issues.openmrs.org/browse/FM2-211
> FM2-211: Update Condition Dao and Service

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPractitionerService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirPractitionerDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterParticipantTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerReferenceTranslatorProviderImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/PractitionerSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterParticipantTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerReferenceTranslatorProviderImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderWebTest.java
Update Practitioner resource to return paged search results.
see https://issues.openmrs.org/browse/FM2-204
> FM2-204: Update Practitioner resource to support paging

- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/MedicationRequestSearchQueryImplTest.java
> Fix formatting issues due to MedicationRequest

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2Test.java
Fixed NPE by adding null check
see https://issues.openmrs.org/browse/FM2-231
> FM2-231: Get condition by bad or non existing UUID throws NPE

- api-2.2/src/test/java/org/openmrs/module/fhir2/api/search/ConditionSearchQueryImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDao.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/AllergyIntoleranceSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/DiagnosticReportSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/EncounterSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/MedicationRequestSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/ObservationSearchQueryImplTest.java
Corrected the functionality of handling references in baseDao to allow OR'ing.
see https://issues.openmrs.org/browse/FM2-233
> FM2-233: Add support for OR'ing references

- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirUserDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirUserDaoImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirUserDaoImplTest.java
> FM2-237: Add method to get user by user name

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/ObservationSearchQueryImplTest.java
Add criterion entries to criteria object for Observation resource for missing handlers
see https://issues.openmrs.org/browse/FM2-236
> FM2-236: Ensure criteria are added to search for Observation

- api/src/main/java/org/openmrs/module/fhir2/api/FhirRelatedPersonService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirRelatedPersonDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirRelatedPersonDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirRelatedPersonServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/RelatedPersonFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/RelatedPersonFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirRelatedPersonDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirRelatedPersonServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/RelatedPersonFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/RelatedPersonFhirResourceProviderTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirRelatedPersonDaoImplTest_intial_data.xml
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/RelatedPersonFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/RelatedPersonFhirResourceProviderWebTest.java
Add search support for related person resources. 
https://issues.openmrs.org/browse/FM2-139
- [ X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [ X] I have **added tests** to cover my changes. (If you refactored
- [X ] I ran `mvn clean package` right before creating this pull request and
- [ X] All new and existing …
> FM2-139: Add initial changes for the related person search.

- api/src/main/java/org/openmrs/module/fhir2/api/FhirServiceRequestService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirServiceRequestDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/ServiceRequestSearchQueryImplTest.java
Update ServiceRequest resource to return paged search results. 
see https://issues.openmrs.org/browse/FM2-227
> FM2-227: Update ServiceRequest resource to support paging

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirTaskService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirTaskDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseServiceRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/TaskSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProviderWebTest.java
Update Task resource to return paged search results.
see https://issues.openmrs.org/browse/FM2-229
> FM2-229: Update Task resource to support paging

- omod/src/test/java/org/openmrs/module/fhir2/narrative/AllergyIntoleranceNarrativeTest.java
- omod/src/test/java/org/openmrs/module/fhir2/narrative/BaseFhirNarrativeTest.java
- omod/src/test/java/org/openmrs/module/fhir2/narrative/ConditionNarrativeTest.java
- omod/src/test/java/org/openmrs/module/fhir2/narrative/MedicationRequestNarrativeTest.java
Instead of trying to grab the first line of the file to compare, remove any trailing white-space.
@gitcliff Would you be able to checkout this branch and confirm whether or not this fixes the issue for you? Travis does not appear to have the ability to run tests on Windows.
see https://issues.openmrs.org/browse/FM2-243
No? -> figure out why and add the fix to your commit. It is your responsibility …
> FM2-243: Fix test errors on Windows

- api/src/main/java/org/openmrs/module/fhir2/providers/util/FhirProviderUtils.java
https://issues.openmrs.org/browse/FM2-225
cc @ibacher  @corneliouzbett .kindly review.
> FM2-225:Add buildDelete static method for FhirProviderUtils

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirPractitionerService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPractitionerDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/PractitionerSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderWebTest.java
Added the following search parameters for Practitioner:
given, family, address-city, address-state, address-country, address-postalcode
see https://issues.openmrs.org/browse/FM2-228
> FM2-228: Improve search for Practitioner resource

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
Updated conditionTranslator
see https://issues.openmrs.org/browse/FM2-232
> FM2-232: Update ConditionTranslator to support non-coded Conditions

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirMedicationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/MedicationSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImplTest_initial_data.xml
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderWebTest.java
Update medication resource to return paged search results
see https://issues.openmrs.org/browse/FM2-205
> FM2-205: Update medication resource to support paging

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2Test.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/search/ConditionSearchQueryImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryBundleProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPersonServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirRelatedPersonServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/DiagnosticReportSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/EncounterSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/ObservationSearchQueryImplTest.java
Changed the paging structure to ensure that only unique results are returned.
see https://issues.openmrs.org/browse/FM2-234
> FM2-234: Ensure search returns unique results

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderWebTest.java
Update MedicationFhirResource Provider delete method.
see https://issues.openmrs.org/browse/FM2-248
- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [ x] I have **added tests** to cover my changes. (If you refactored
- [ x] I ran `mvn clean package` right before creating this pull request and
- [x ] All new and …
> FM2-248:-Update MedicationFhirResource Provider delete method.

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProviderWebTest.java
Add delete operation for diagnosticReport resource.
https://issues.openmrs.org/projects/FM2/issues/FM2-214
- [ X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [ X] I have **added tests** to cover my changes. (If you refactored
- [ X] I ran `mvn clean package` right before creating this pull request and
- [X ] All new …
> FM2-214: Add delete operation for diagnostic report resource.

- pom.xml
see https://issues.openmrs.org/browse/TRUNK-5795
or: https://talk.openmrs.org/t/fhir2-module-causing-linkage-error-with-name-javax-xml-namespace-qname/28675/20
> TRUNK-5795: LinkageError javax/xml/namespace/QName

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImplTest.java
- Change mapping for `Practitioner.identifier` from `User.UserId` to `User.SystemId`
see https://issues.openmrs.org/browse/FM2-235
> FM2-235: Update identifier in UserTranslator

- api/src/main/java/org/openmrs/module/fhir2/api/FhirAllergyIntoleranceService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirAllergyIntoleranceDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/AllergyIntoleranceFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/AllergyIntoleranceSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/AllergyIntoleranceFhirR3ResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/AllergyIntoleranceFhirR3ResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProviderWebTest.java
link:https://issues.openmrs.org/browse/FM2-101
> FM2-101:Implement sorting for AllergyIntolerance resource

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProviderWebTest.java
https://issues.openmrs.org/browse/FM2-224
cc @ibacher @corneliouzbett
> FM2-224:Add delete method to Task

- api/src/main/java/org/openmrs/module/fhir2/api/translators/AllergyIntoleranceCategoryTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/AllergyIntoleranceReactionComponentTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceCategoryTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceReactionComponentTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceCategoryTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceReactionComponentTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImplTest.java
Refactor ReactionComponent and Category into translators for AllergyIntolerance Resource
see https://issues.openmrs.org/browse/FM2-181
> FM2-181: Refactor ReactionComponent and Category into translators

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProviderWebTest.java
see https://issues.openmrs.org/browse/FM2-218
> FM2-218 Add create, update, and delete methods for MedicationRequest

- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProviderWebTest.java
Fix web tests for delete method in Task, Medication and DiagnosticReport resources
> Fix web tests for delete method

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ListFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ListFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/ListFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ListFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/ListFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ListFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ListResourceWebTest_create.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ListResourceWebTest_update.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ListResourceWebTest_updateWithWrongId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ListResourceWebTest_updateWithoutId.json
Add create, update, and delete methods for List.
https://issues.openmrs.org/projects/FM2/issues/FM2-216?filter=myopenissues
- [ X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [ X] I have **added tests** to cover my changes. (If you refactored
- [ X] I ran `mvn clean package` right before creating this pull request and
No? -> execute above …
> FM2-216 :- Add create, update, and delete methods for List.

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ObservationResourceWebTest_create.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ObservationResourceWebTest_update.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ObservationResourceWebTest_updateWithWrongId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ObservationResourceWebTest_updateWithoutId.json
Add create, update and delete methods for observation
see https://issues.openmrs.org/browse/FM2-219
> FM2-219: Add create, update and delete methods for observation

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/EncounterWebTest_Create.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/EncounterWebTest_Update.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/EncounterWebTest_UpdateWithWrongId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/EncounterWebTest_UpdateWithoutId.json
Add create, update, and delete methods for Encounter.
https://issues.openmrs.org/projects/FM2/issues/FM2-215?filter=myopenissues
- [X ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [X ] I have **added tests** to cover my changes. (If you refactored
- [ X] I ran `mvn clean package` right before creating this pull request and
No? -> execute above …
> FM2-215: Add create, update, and delete methods for Encounter.

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProvider.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/MedicationRequestResourceWebTest_create.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/MedicationRequestResourceWebTest_update.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/MedicationRequestResourceWebTest_updateWithWrongId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/MedicationRequestResourceWebTest_updateWithoutId.json
Add web tests to MedicationRequest resource
see https://issues.openmrs.org/browse/FM2-250
> FM2-250: Add web tests to MedicationRequest resource

- omod/src/main/java/org/openmrs/module/fhir2/web/util/FhirVersionUtils.java
- omod/src/test/java/org/openmrs/module/fhir2/web/util/FhirVersionUtilsTest.java
fixes version determination when there is no trailing slash
see https://issues.openmrs.org/browse/FM2-263
> FM2-263: Determine version when there is not trailing slash

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionClinicalStatusTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConditionClinicalStatusTranslatorImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
see https://issues.openmrs.org/browse/FM2-260
> FM2-260: Fix the binding for Condition.clinicalStatus

- omod/src/test/java/org/openmrs/module/fhir2/web/util/FhirVersionUtilsTest.java
Fixes some formatting issues from a recent commit.
This is just three white space changes that I introduced recently and is a nuisance so I did not create an issue for this.
> Fixes some formatting issues from a recent commit.

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionClinicalStatusTranslatorImpl_2_2.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceReactionComponentTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ListTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationAddressTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientIdentifierTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonAddressTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/RelatedPersonTranslatorImpl.java
There were missing null checks at various points in the translators. This PR deals with adding them to avoid NullPointerExceptions.
> Add null checks to translators

- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ServiceRequestWebTest_UpdateWithWrongId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ServiceRequestWebTest_UpdateWithoutId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ServiceRequestWebTest_create.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ServiceRequestWebTest_update.json
LINK:https://issues.openmrs.org/browse/FM2-223
> FM2-223: Add create, update, and delete methods for ServiceRequest

- api/src/main/java/org/openmrs/module/fhir2/api/search/param/SearchParameterMap.java
Added null check to SearchParameterMap
> Added null check to SearchParameterMap

- api/src/main/java/org/openmrs/module/fhir2/api/FhirServiceRequestService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirServiceRequestDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirServiceRequestServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirServiceRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/ServiceRequestSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProviderTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirServiceRequestTest_initial_data.xml
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ServiceRequestWebTest_UpdateWithWrongId.json
Add search parameter for ServiceRequest
see https://issues.openmrs.org/browse/FM2-238
> FM2-238: Add search parameter for ServiceRequest

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirLocationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/BaseFhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryIncludeImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/LocationSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderWebTest.java
Add search for _include using Location:partof
see https://issues.openmrs.org/browse/FM2-246
> FM2-246: Add search for _include using Location:partof

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProviderWebTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ProcedureRequestWebTest_create.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ProcedureRequestWebTest_update.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ProcedureRequestWebTest_updateWithWrongId.json
- omod/src/test/resources/org/openmrs/module/fhir2/providers/ProcedureRequestWebTest_updateWithoutId.json
Add create, update and delete methods for ProcedureRequest
see https://issues.openmrs.org/browse/FM2-267
> FM2-267: Add create, update and delete methods for ProcedureRequest

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirDiagnosticReportService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirDiagnosticReportDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/DiagnosticReportSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProviderWebTest.java
Add search for DiagnosticReport?result
see https://issues.openmrs.org/browse/FM2-278
> FM2-278: Add search for DiagnosticReport.result

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirUserService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirUserDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirUserDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirUserServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerReferenceTranslatorUserImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirUserDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirUserServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/UserSearchQueryImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerReferenceTranslatorUserImplTest.java
- api/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirUserDaoImplTest_initial_data.xml
see https://issues.openmrs.org/browse/FM2-186
> FM2-186: Add support for users as Practitioners

- api/src/main/java/org/openmrs/module/fhir2/api/FhirUserService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirUserDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirUserDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirUserServiceImplTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/util/NarrativeUtilTest.java
Just did `mvn clean package` from a clean branch to get rid of these automatically applied style changes.
NA
> automatic style fixes

- omod/src/main/java/org/openmrs/module/fhir2/web/filter/AuthenticationFilter.java
> Expose conformance statement without authentication

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirGlobalPropertyDaoImpl.java
see https://issues.openmrs.org/browse/FM2-296
No because the current unit tests already cover my change which is only a performance improvement.
> Replaces criteria based GlobalProperty fetching with get().

- omod/src/main/resources/org/openmrs/module/fhir2/narratives/AllergyIntolerance.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/Condition.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/Encounter.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/MedicationRequest.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/Observation.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/Person.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/Practitioner.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/PractitionerRole.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/RelatedPerson.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/ServiceRequest.html
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/Task.html
Added checks for empty resources or resource properties in narrative templates.
see https://issues.openmrs.org/browse/FM2-281
> FM2-281: Add checks for empty properties in narrative templates

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProviderIntegrationTest.java
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/MedicationRequest.html
Add Integration Tests for MedicationRequest. This includes tests for the read and search functionality.
see https://issues.openmrs.org/browse/FM2-288
> FM2-288: Add Integration Tests for MedicationRequest

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirDiagnosticReportDaoImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirDiagnosticReportDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/DiagnosticReportSearchQueryTest.java
Fix DiagnosticReport to return Obs having group members
> Fix DiagnosticReport to return Obs having group members

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationDaoImpl.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderIntegrationTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderWebTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/MedicationResourceWebTest_create.json
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/MedicationResourceWebTest_update.json
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/MedicationWebTest_create.xml
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/MedicationWebTest_update.xml
* Added Integration tests for Medication resource
see https://issues.openmrs.org/browse/FM2-287
> FM2-287: Add Integration tests for Medication

- api-2.2/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/BaseFhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirCohortListServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirRelatedPersonServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/BaseFhirIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/BaseFhirR3IntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/BaseFhirR4IntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderIntegrationTest.java
Improves the integration tests for Patient adding checks for error conditions and a few changes to support these new tests.
see https://issues.openmrs.org/browse/FM2-294
> FM2-294: Improve integration tests for Patient

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/LocationTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderIntegrationTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/LocationWebTest_create.json
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/LocationWebTest_create.xml
Add Integration Tests for Location
see https://issues.openmrs.org/browse/FM2-286
> FM2-286: Add Integration Tests for Location

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderIntegrationTest.java
For now, I have added integration tests for:
* `Get `
* `Delete`
* A few `Search` operations
Todo:
`Create` & `Update` 
- I want to look into adding mapping for visits to FhirEncounter
see https://issues.openmrs.org/browse/FM2-285 …
> FM2-285: Add Integration Tests for Encounter

- api/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderTest.java
Fix unit tests for practitioner resource providers
> Fix unit tests for practitioner resource providers

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProvider.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProviderIntegrationTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/ProcedureRequestFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProviderWebTest.java
Add Integration Tests for ServiceRequest and ProcedureRequest
see https://issues.openmrs.org/browse/FM2-292
> FM2-292: Add Integration Tests for ServiceRequest and ProcedureRequest

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderIntegrationTest.java
Improve Integration Tests for Medication
see https://issues.openmrs.org/browse/FM2-301
> FM2-301: Improve Integration Tests for Medication

- api/pom.xml
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseReferenceHandlingTranslator.java
- api/src/main/resources/moduleApplicationContext.xml
- pom.xml
Adding the `hapi-fhir-client` dependency for improved compatibility with other OpenMRS modules
see https://issues.openmrs.org/browse/FM2-300
> FM2-300: Add HAPI Client

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/PersonFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PersonFhirResourceProviderIntegrationTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImplTest_initial_data.xml
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/PersonWebTest_create.json
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/PersonWebTest_create.xml
LINK:https://issues.openmrs.org/browse/FM2-290
> FM2-290: Add Integration Tests for Person

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderIntegrationTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/PractitionerWebTest_create.json
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/PractitionerWebTest_create.xml
Create Integration Tests for Practitioner
see https://issues.openmrs.org/browse/FM2-305
- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [x ] I have **added tests** to cover my changes. (If you refactored
- [ x] I ran `mvn clean package` right before creating this pull request and
- [x ] All new and existing …
> FM2-305: Create Integration Tests for Practitioner.

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConditionDaoImpl_2_2.java
- Removes `HISTORY_OF` condition clinical status. Not a valid FHIR spec value
see https://issues.openmrs.org/browse/FM2-325
> FM2-325: Remove history-of condition clinical from condition dao class

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/RelatedPersonTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/RelatedPersonTranslatorImplTest.java
- omod/src/test/java/org/openmrs/module/fhir2/narrative/BaseFhirNarrativeTest.java
see https://issues.openmrs.org/browse/FM2-191
> FM2-191: Add support for estimated birthdates

- api/pom.xml
- pom.xml
> Update to HAPI 5.2.1

- api-2.1/src/test/java/org/openmrs/module/fhir2/api/translators/impl/GroupTranslatorImpl_2_1Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseGroupTranslator.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/BaseGroupTranslatorTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/GroupTranslatorImplTest.java
Added mapping for  `managingEntity` group property
* Group.managingEntity <--> Cohort.creator
see https://issues.openmrs.org/browse/FM2-342
> FM2-342: Add mapping for managingEntity group resource

- api-2.1/pom.xml
- api-2.1/src/test/java/org/openmrs/module/fhir2/TestFhirSpringConfiguration.java
- api-2.1/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirGroupDaoImpl_2_1Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirGroupDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirGroupServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/GroupFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirGroupServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/GroupSearchQueryTest.java
Implement search for groups by the practitioner or rather the creator in openMRS;
- uuid - User UUID
- uuid - Person UUID (`_id`)
- given_name
- family_name
- name - Full names
see https://issues.openmrs.org/browse/FM2-343
> FM2-343: Implement search operations for group resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/EncounterTypeTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseEncounterTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTypeTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTypeTranslatorImplTest.java
Added support for translating between the `Encounter.type` field (https://www.hl7.org/fhir/encounter-definitions.html#Encounter.type) and an OpenMRS `EncounterType` object.
see https://issues.openmrs.org/browse/FM2-332
> FM2-332: Map Encounter Type Field

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/VisitTypeTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/VisitTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/VisitTypeTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/VisitTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/VisitTypeTranslatorImplTest.java
see https://issues.openmrs.org/browse/FM2-350
> FM2-350: Add support for mapping visit types to the Encounter.type field

- api/src/main/java/org/openmrs/module/fhir2/model/FhirDurationUnitMap.java
- api/src/main/java/org/openmrs/module/fhir2/model/FhirEncounterClassMap.java
- api/src/main/java/org/openmrs/module/fhir2/model/FhirObservationCategoryMap.java
This PR add `@Deprecated` annotation to isRetired methods which eliminates 3 warnings during project building.
see https://issues.openmrs.org/browse/FM2-361
> FM2-361: Get rid of warnings by adding @Deprecated annotation

- test-data/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest_owner_data.xml
see https://issues.openmrs.org/browse/FM2-378
> FM2-378: Remove TODO comments in FhirTaskDaoImplTest_owner_data.xml

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirEncounterService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/BaseFhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/FhirUtils.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderIntegrationTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderWebTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/EncounterWebTest_create.xml
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/EncounterWebTest_update.json
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/VisitWebTest_create.json
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/VisitWebTest_create.xml
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/VisitWebTest_update.json
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/VisitWebTest_updateWithWrongId.json
see https://issues.openmrs.org/browse/FM2-352
> FM2-352: Add support for creating encounters via the FHIR API

- api/src/main/java/org/openmrs/module/fhir2/api/FhirClientService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirClientServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirClientServiceImplTest.java
…ts for Fhir versions 3 and 4
FM2-357: Created a class, interface, and test for creating Fhir clients for Fhir versions 3 and 4
see https://issues.openmrs.org/browse/FM2-357
- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [x ] I have **added tests** to cover my changes. (If you refactored
- [x ] I ran `mvn clean package` right before creating this pull request and
added all …
> FM2-357: Add a service to get a FHIR client

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirObservationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/ObservationSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderWebTest.java
see https://issues.openmrs.org/browse/FM2-393
> FM2-393: Add support for $lastn in Observations R4

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImplTest.java
see https://issues.openmrs.org/browse/FM2-405
> FM2-405: Do not tie Person active state to voided state

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirPatientService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQuery.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/PatientSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderWebTest.java
see https://issues.openmrs.org/browse/FM2-411
> FM2-411: Added support for instance level $everything operation on Patients in R4

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirR3ResourceProviderWebTest.java
… in R3
see https://issues.openmrs.org/browse/FM2-412
> FM2-412: Support for instance level $everything operation on Patients in R3

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirR3ResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderWebTest.java
see https://issues.openmrs.org/browse/FM2-419
> FM2-419: Support for type level $everything operation on Patients in R3

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderIntegrationTest.java
see https://issues.openmrs.org/browse/FM2-420
> FM2-420: Integration tests for type level $everything operation on Patients

- api/src/main/java/org/openmrs/module/fhir2/api/FhirEncounterService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/EncounterSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderWebTest.java
see https://issues.openmrs.org/browse/FM2-425
> FM2-425: Support for instance-level $everything operation on Encounters in R4

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseReferenceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/BaseReferenceHandlingTranslatorTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
Add support for observations with a location value by returning a reference to a Location using Observation's valueText.  
cc @mozzy11 @ibacher 
see https://issues.openmrs.org/browse/FM2-422
> FM2-422: Add support for observations with a location value

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientIdentifierTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientIdentifierTranslatorImplTest.java
Add the IdentifierType UUID to the patient identifer type field
see https://issues.openmrs.org/browse/FM2-435
> FM2-435: Add the IdentifierType UUID to the patient identifer type field

- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirLocationDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirLocationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/BaseFhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/LocationTagTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTagTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTagTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderIntegrationTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/providers/LocationWebTest_create.json
see https://issues.openmrs.org/browse/FM2-444
> FM2-444: Add the ability to save Location Tags

- omod/src/main/java/org/openmrs/module/fhir2/web/authentication/RequireAuthenticationInterceptor.java
- omod/src/main/java/org/openmrs/module/fhir2/web/filter/AuthenticationFilter.java
- omod/src/main/java/org/openmrs/module/fhir2/web/servlet/FhirRestServlet.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/BaseFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/authentication/RequireAuthenticationInterceptorTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/filter/AuthenticationFilterTest.java
see https://issues.openmrs.org/browse/FM2-443
> FM2-443: AuthenticationFilter to allow requests with other authentication schemes to go through

- api/src/main/resources/liquibase.xml
see https://issues.openmrs.org/browse/FM2-452
> FM2-452: Drop unique key constraint

- api/src/main/java/org/openmrs/module/fhir2/api/FhirEncounterService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryInclude.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/EncounterSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderWebTest.java
Implemented sorting by date for Encounters
see https://issues.openmrs.org/browse/FM2-408
> FM2-408: Encounters should be sortable by date

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirTaskService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryInclude.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseServiceRequestTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/TaskSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ServiceRequestFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProviderWebTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest_owner_data.xml
see https://issues.openmrs.org/browse/FM2-458
> FM2-458: Add Support for _include for the Task FHIR Search

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseReferenceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTypeTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientIdentifierTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/VisitTypeTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/FhirUtils.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImplTest.java
Adds support for the ui-framework-style localization of metadata.
see https://issues.openmrs.org/browse/FM2-346
> FM2-346: Support i18n for metadata

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImplTest.java
see https://issues.openmrs.org/browse/FM2-471
see https://talk.openmrs.org/t/mapping-drugs-to-fhir-medications/36414
> FM2-471: MedicationRequest should populate custom OpenMRS DrugName field

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/CodingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/MedicationRequestDispenseRequestComponentTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/DosageTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationQuantityCodingTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestDispenseRequestComponentTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/ObservationSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/DosageTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationQuantityCodingTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestDispenseRequestComponentTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImplTest.java
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/MedicationRequest.html
See:  https://issues.openmrs.org/projects/FM2/issues/FM2-463
> FM2-463: Map DrugOrder Dose and Dose Units to MedicationRequest

- api/src/main/java/org/openmrs/module/fhir2/model/FhirDiagnosticReport.java
- api/src/main/java/org/openmrs/module/fhir2/model/FhirTaskParam.java
- api/src/main/resources/liquibase.xml
> update fhir_diagnostic_report table

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImplTest.java
See:  https://issues.openmrs.org/browse/FM2-472
> FM2-472: MedicationRequest should support Drug Orders without Drugs

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonAddressTranslatorImpl.java
FM2-485 Add District Mapping to person address translator
https://issues.openmrs.org/browse/FM2-485
> FM2-485: Add District Mapping to person address translator

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderIntegrationTest.java
…so far
see https://issues.openmrs.org/browse/FM2-430
> FM2-430: Integrations tests for instance-level operation on Encounters

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImpl.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderIntegrationTest.java
> fix practitioner.active translator

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonAddressTranslatorImpl.java
[FM2-485](https://issues.openmrs.org/browse/FM2-485) which attempts to add 'District' mapping to the person address translator has only the mapping from the OpenMRS object to the FHIR object and is missing the reverse mapping from FHIR to OpenMRS.
So, in spite of [this PR](https://github.com/openmrs/openmrs-module-fhir2/pull/412) the mapping doesn't happen correctly and the 'District' field fails to get pushed to the Database on new Patient creation.
see https://issues.openmrs.org/browse/FM2-486
No? -> write tests and add them to this commit `git …
> FM2-486: Adding mapping for district for FHIR -> OMRS

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseCodingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationQuantityCodingTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationQuantityCodingTranslatorImpl.java
- add toOpenmrsType() base implementation in BaseCodingTranslator
see https://issues.openmrs.org/browse/FM2-64
> FM2-64: minor cleanup of BaseCodingTranslator

- .github/workflows/main.yml
- docker/Dockerfile
- docker/csrfguard.properties
- docker/docker-compose-refqa.yml
- e2e-tests/pom.xml
- e2e-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientDomainTest.java
- pom.xml
Create a real integration test for the Patient domain using [HAPI-Generic-Client ](https://hapifhir.io/hapi-fhir/docs/client/generic_client.html)
see https://issues.openmrs.org/browse/FM2-460
> FM2-460: Create a real integration test for the Patient domain

- pom.xml
This PR is about:
- Changes scope of commons-io dependency to provided to resolve conflict from openmrs
- Please refer below card for more details 
https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/41?modal=detail&selectedIssue=BAH-2028
> BAH-2028 - | Rohit | - Changes scope of commons-io dependency to provided to resolve conflict from openmrs

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImplTest.java
- omod/src/main/java/org/openmrs/module/fhir2/web/util/DisableCacheInterceptor.java
…
see https://issues.openmrs.org/browse/FM2-501
> FM2-501: Update The Concept Translator to Map Concept Sources not mapped as "SAME-AS"

- api/src/main/java/org/openmrs/module/fhir2/api/util/GeneralUtils.java
- omod/src/main/resources/config.xml
> remove comment from conditional resources tag to fix module not starting

- api/src/main/java/org/openmrs/module/fhir2/api/FhirConceptService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirConceptDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirConceptDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConceptServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirConceptDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConceptServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationQuantityCodingTranslatorImplTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirConceptDaoImplTest_initial_data.xml
see https://issues.openmrs.org/browse/FM2-501
> update Concept translator to map FHIR codes to concepts with any source mapping

- api/src/main/java/org/openmrs/module/fhir2/api/FhirLocationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryInclude.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/LocationSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirLocationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/LocationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderWebTest.java
- Added LocationSearchParams class that extends the BaseResourceSearchParams.
- Refactor all provider classes (r3 and r4).
- Ensure all tests are passing
> FM2-481: Clean up parameter passing in Location Service class search method

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationDispenseFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationDispenseFhirResourceProvider.java
Update MedicationDispense providers with necessary annotations
> Update MedicationDispense providers with necessary annotations

- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/EncounterSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderTest.java
- make use of BaseResourceSearchParams for Encounter search parameter mapping
Note: This is a continuation of work done in https://github.com/openmrs/openmrs-module-fhir2/pull/404 but for the Encounter resource
No? Unsure? -> execute command …
> FM2-481: refactoring EncounterSearchParams to use new BaseResourceSearchParams class

- api-2.6/src/test/java/org/openmrs/module/fhir2/api/search/EncounterSearchQueryImpl_2_6Test.java
- api-2.6/src/test/java/org/openmrs/module/fhir2/api/search/MedicationRequestSearchQueryImpl_2_6Test.java
- api-2.6/src/test/java/org/openmrs/module/fhir2/api/search/MedicationSearchQueryImpl_2_6Test.java
- api-2.6/src/test/java/org/openmrs/module/fhir2/api/search/PatientSearchQueryImpl_2_6Test.java
- api-2.6/src/test/java/org/openmrs/module/fhir2/api/search/PractitionerSearchQueryImpl_2_6Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseEncounterDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/EncounterSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/MedicationRequestSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/MedicationSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/PatientSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/PractitionerSearchQueryTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest_initial_data.xml
- test-data/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImpl_initial_data.xml
> FM2-532: MedicationRequest endpoint should not return Discontinue Orders

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/model/FhirTask.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/FhirTaskTranslatorImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceIntegrationTest.java
- test-data/src/test/resources/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest_initial_data.xml
see https://issues.openmrs.org/browse/FM2-531
> FM2-531 : Add Location Reference to the Task resource and Fix failing tests

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImplTest.java
> FM2-540: Support expansion of Medication Request statuses

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPersonDaoImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/EncounterSearchQueryTest.java
> FM2-534: Searching should provide method to ensure consistent sort order

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImpl_2_2Test.java
> FM2-480: Support expansion of Medication Request statuses

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImpl_2_2Test.java
- api-2.6/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationDispenseTranslatorImpl_2_6.java
- api-2.6/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationDispenseTranslatorImpl_2_6Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImplTest.java
> FM2-556: FHIR Translators should not overwrite audit fields

- omod/src/main/java/org/openmrs/module/fhir2/web/util/DisableCacheInterceptor.java
Disables browser caching with the 'no-store' strategy
see https://issues.openmrs.org/browse/O3-1820
> O3-1820: Disable browser caching 

- integration-tests-2.2/src/test/java/org/openmrs/module/fhir2/provider/r3/EncounterFhirResourceProvider_2_2IntegrationTest.java
- integration-tests-2.2/src/test/java/org/openmrs/module/fhir2/provider/r4/EncounterFhirResourceProvider_2_2IntegrationTest.java
Added missing license headers
see https://issues.openmrs.org/browse/FM2-561
> Aadd missing license headers to some files

- api-2.6/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationDispenseTranslatorImpl_2_6.java
- api-2.6/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationDispenseTranslatorImpl_2_6Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
see https://issues.openmrs.org/browse/FM2-563
> FM2-563: Medication Dispense: Add Recorded Extension

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestStatusTranslatorImpl_2_2Test.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestTranslatorImpl.java
> FM2-566: Add Fulfiller Status Extension to MedicationRequest

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProvider.java
> FM2-567: Add Create, Update and Delete annotations on Medication Request

- omod/src/main/resources/config.xml
Related to https://issues.openmrs.org/browse/TRUNK-6054
> FHIR2 to not be aware of legacyui module

- api-2.1/src/main/java/org/openmrs/module/fhir2/api/translators/impl/GroupComponentTranslatorImpl.java
- api-2.2/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl_2_2.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/AllergyIntoleranceTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseGroupTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConditionTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/LocationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorProviderImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PractitionerTranslatorUserImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/VisitTranslatorImpl.java
The `toOpenmrsType` translators have been changed to set the **uuid** to the id part of the id, not the full id._**ie**_, the uuid should be set to:`cea2cff8-ab6d-42a1-a6fc-e3edb7b39631` not: `Encounter/cea2cff8-ab6d-42a1-a6fc-e3edb7b39631`.
see https://issues.openmrs.org/browse/FM2-570 …
> FM2-570: toOpenmrsType translators should set uuid to id part of id, not full id

- api/src/main/java/org/openmrs/module/fhir2/api/FhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/BaseFhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationDispenseServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/JsonPatchUtils.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/util/JsonPatchUtilTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/BaseFhirIntegrationTest.java
Ensure that we can support json patches too  since json merge patches have a limitation when it comes to patching attributes inside Arrays, Lists, etc..
**Previously**
Since the Hapi/fhir PatchTypeEnum enum class doesn't really cater for `JSON MERGE PATCH`, in the previous implementation in this module, Mark sort of shoe-horned it in hence why Json merge patch and Json patch were both coming across as the same type since we needed to use one of the values in PatchTypeEnum (which doesn’t support Merge Patch), so we hack around this by temporarily making it appear that a merge patch request is actually a JSON patch request. The logic for that is here.
**Now**
We have an `if-else` statement under `JSON_PATCH` because both merge patches and normal patches will come in under that. What i did …
> Fm2-579-impl: Add support for Json Patch operations - Patient Resource

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirObservationDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/BaseResourceSearchParams.java
> FM2-572: Improve performance for total count in results

- api/src/main/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProvider.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Practitioner_json_merge_patch.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Practitioner_json_patch.json
Ensure the Practitioner Resource Provider(R4) can support JSON_MERGE_PATCH and JSON_PATCH patch operations.
see https://issues.openmrs.org/browse/FM2-583
> FM2-583: Add support for Json Merge Patch operations - Practitioner Resource

- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ConditionFhirResourceProvider.java
- integration-tests-2.2/src/test/java/org/openmrs/module/fhir2/provider/r4/ConditionResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Condition_json_merge_patch.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Condition_json_patch.json
Ensured the condition resource can support json merge patch operations and this has been tested using the integration test as well as on an openmrs instance.
see https://issues.openmrs.org/browse/FM2-576
> FM2-576: Add support for Json patching operations - Condition Resource

- integration-tests-2.2/src/test/java/org/openmrs/module/fhir2/provider/r4/MedicationRequestFhirResourceProvider_2_2IntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/MedicationRequest_json_patch.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/MedicationRequest_xml_patch.xml
This ticket introduces [XML PATCH](https://www.rfc-editor.org/rfc/rfc7351) operations to the MedicationRequest Resource.
```
<replace sel="/fhir:MedicationRequest/fhir:extension/fhir:valueCode">
<valueCode value="COMPLETED"/>
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-601
added all formatting changes to my …
> Add support for XML PATCHing operations - MedicationRequest Resource

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/DiagnosticReport_xml_patch.xml
This ticket introduces [XML PATCH](https://www.rfc-editor.org/rfc/rfc7351) operations to the DiagnosticReport Resource.
```
<replace sel="/fhir:DiagnosticReport/fhir:status/@value">
registered
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-600
No? -> figure out why and add the fix to …
> FM2-600: Add support for XML PATCHing operations - DiagnosticReport Resource

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Medication_json_patch.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Medication_patch.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Medication_xml_patch.xml
This ticket introduces [XML PATCH](https://www.rfc-editor.org/rfc/rfc7351) operations to the Medication Resource.
```
<replace sel="/fhir:Medication/fhir:ingredient/fhir:itemCodeableConcept/fhir:coding/fhir:code/@value">
5086AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-599
added all …
> FM2-599: Add support for XML PATCHing operations - Medication Resource

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Task_xml_patch.xml
This ticket introduces [XML PATCH](https://www.rfc-editor.org/rfc/rfc7351) operations to the Task Resource.
```
<replace sel="/fhir:Task/fhir:status/@value">
requested
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-598
No? -> figure out why and …
> FM2-598: Add support for XML PATCHing operations-Task Resource

- integration-tests-2.6/src/test/java/org/openmrs/module/fhir2/provider/r4/MedicationDispenseFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/MedicationDispense_xml_patch.xml
This ticket introduces [XML PATCH](https://www.rfc-editor.org/rfc/rfc7351) operations to the `MedicationDispense` Resource.
```
<replace sel="/fhir:MedicationDispense/fhir:status/@value">
completed
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-597
No? -> execute above …
> FM2-597: Add support for XML PATCHing operations-MedicationDispense Resource

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Practitioner_xmlpatch.xml
This pull request introduces [XML PATCHing](https://www.rfc-editor.org/rfc/rfc7351) operations to the Practitioner Resource.
```
<replace sel="/fhir:Practitioner/fhir:gender/@value">
female
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-596
No? -> figure out why and add the fix to …
> FM2-596: Add support for XML patching operations - Practitioner Resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/MedicationSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderIntegrationTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationFhirResourceProviderWebTest.java
> FM2-481: Clean up parameter passing for Medication Service Search method

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPractitionerService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/PractitionerSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPractitionerServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderIntegrationTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/PractitionerFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PractitionerFhirResourceProviderWebTest.java
> FM2-481: Clean up parameter passing for Practitioner Service Search method

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/LocationFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Location_xml_patch.xml
This ticket introduces [XML PATCH](https://www.rfc-editor.org/rfc/rfc7351) operations on the Location Resource.
For example the following xml doc should be supported:
```
<replace sel="/fhir:Location/fhir:name/@value">Patched Location</replace>
<replace sel="/fhir:Location/fhir:address">
<address>
<city value="Wakiso"/>
<country value="Uganda"/>
<postalCode value="0000 WK"/>
<state value="Central Region"/>
</address>
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-592
existing code that was well tested you do not …
> FM2-592: Add support for XML PATCH operation - Location Resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirMedicationRequestService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryInclude.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/MedicationRequestSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirMedicationRequestServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/MedicationRequestFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/MedicationRequestFhirResourceProviderWebTest.java
> FM2-481: Clean up parameter passing for MedicationRequest Service Search

- api/src/main/java/org/openmrs/module/fhir2/api/impl/BaseFhirService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirObservationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/ObservationWebTest_json_patch.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/ObservationWebTest_patch.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/ObservationWebTest_update.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/ObservationWebTest_update.xml
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/ObservationWebTest_xml_patch.xml
- In the first commit, i am ensuring the Observation resource supports UPDATE(PUT) which is solves the issue at https://issues.openmrs.org/browse/FM2-603
- In the second commit, i am ensuring the Observation resource supports PATCH operations which solves the issue at https://issues.openmrs.org/browse/FM2-578
[Screencast from 18-07-23 10:23:34.webm](https://github.com/openmrs/openmrs-module-fhir2/assets/47120265/95afb4dc-00d3-47e0-95a1-85fbb626eca7)
see https://issues.openmrs.org/browse/FM2-603
No? -> write tests and add them to this commit `git …
> FM2-603: Add Support for UPDATE on the Observation Resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirAllergyIntoleranceService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryInclude.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/FhirAllergyIntoleranceSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/AllergyIntoleranceFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirAllergyIntoleranceServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/AllergyIntoleranceFhirR3ResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/AllergyIntoleranceFhirR3ResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProviderWebTest.java
> FM2-481: Clean up parameter passing for AllergyIntolerance Service Search

- api/src/main/java/org/openmrs/module/fhir2/api/FhirContactPointMapService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirContactPointMapDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirContactPointMapDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirContactPointMapServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirContactPointMapDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirContactPointMapServiceImplTest.java
see https://issues.openmrs.org/browse/FM2-612
> FM2-612: Ensure FhirContactPointMapService class provides the getFhirContactPointMapByUuid() method

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirPatientService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirGroupDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/OpenmrsPatientSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/PatientSearchQueryTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderIntegrationTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/PatientFhirR3ResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PatientFhirResourceProviderWebTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/api/dao/impl/FhirPatientDaoImplTest_initial_data.xml
Adds a `_query=openmrsPatients` search which takes the usual patient-search parameters and `q` as a filter on the patient name or identifier.
see https://issues.openmrs.org/browse/FM2-614
> FM2-614: Support for an "openmrsPatients" query

- api/src/main/java/org/openmrs/module/fhir2/api/FhirRelatedPersonService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirRelatedPersonServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/RelatedPersonSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/RelatedPersonFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/RelatedPersonFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirRelatedPersonServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/RelatedPersonFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/RelatedPersonFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/RelatedPersonFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/RelatedPersonFhirResourceProviderWebTest.java
> FM2-481: Clean up parameter passing for RelatedPerson Service class

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestDispenseRequestComponentTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/MedicationRequestDispenseRequestComponentTranslatorImplTest.java
> FM2-620: MedicationRequestTranslator converts null refilled allowed to 0 refills allowed

- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirPatientIdentifierSystemDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientIdentifierSystemDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirPatientIdentifierSystemDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPatientServiceImplTest.java
Enables retrieval of PatientIdentifierType objects by their URL via the system, which takes precedence over the identifier type text when available.
see https://issues.openmrs.org/browse/FM2-617
> FM2-617: Use system to differentiate patient identifer types

- pom.xml
This removes `liquibase-api` and `commons-io` from the OMOD, both of which are supplied by the platform and should resolve the issue with the FHIR2 activator.
Thanks @mogoodrich for pointing out the bug!
see https://issues.openmrs.org/browse/FM2-613 …
> FM2-613: Remove unnecessarily packaged modules

- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ValueSetTranslatorImplTest.java
In essence, this removes the `BaseModuleContextSensitiveTest` from the unit test for the `ValueSetTranslatorImplTest` since it seemed to only be required to instantiate the mocks.
see https://issues.openmrs.org/browse/FM2-635 …
> FM2-635: ValueSetTranslatorImplTest relies on hidden context

- api-2.7/pom.xml
- api-2.7/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImpl_2_7.java
- api-2.7/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImpl_2_7Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/ObservationReferenceRangeTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationTranslatorImplTest.java
- omod/pom.xml
- pom.xml
see https://issues.openmrs.org/browse/FM2-659
> FM2-659 - Add support for reference ranges

- omod/src/main/resources/config.xml
> Update module descriptor

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ImmunizationTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirImmunizationServiceImplTest.java
This PR changes `OPENMRS_FHIR_EXIT_IMMUNIZATION_NEXT_DOSE_DATE` to `OPENMRS_FHIR_EXT_IMMUNIZATION_NEXT_DOSE_DATE` for consistency with other extension constants in `FhirConstants.java`.
> FM2-666: Fix typo in immunization next dose date constant name
