openmrs/openmrs-module-fhir2

- api/src/main/java/org/openmrs/module/fhir2/providers/r3/AllergyIntoleranceFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/AllergyIntoleranceFhirR3ResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderTest.java
https://issues.openmrs.org/browse/FM2-178
Added an option parameter "patient" that is evaluated before subject.
> FM2-178: Add patient search parameter where subject is allowed

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- omod/pom.xml
- omod/src/main/java/org/openmrs/module/fhir2/web/servlet/FhirRestServlet.java
- pom.xml
Set Thymeleaf Narrative Generator (with `propFile` as the properties file of HAPI FHIR) while initialising `FhirRestServlet`.
see https://issues.openmrs.org/browse/FM2-193
> FM2-193: Generate default narratives provided by HAPI FHIR

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- omod/src/main/java/org/openmrs/module/fhir2/web/filter/ForwardingFilter.java
- omod/src/main/java/org/openmrs/module/fhir2/web/util/FhirVersionUtils.java
- omod/src/test/java/org/openmrs/module/fhir2/web/util/FhirVersionUtilsTest.java
When the /ws/* paths are forwarded to /ms/* ones, FHIR version determination fails which causes the mentioned bug. This change fixes that bug.
see https://issues.openmrs.org/browse/FM2-259
> fixes version determination for /ms/ paths

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- omod/src/main/java/org/openmrs/module/fhir2/web/servlet/FhirRestServlet.java
- omod/src/main/java/org/openmrs/module/fhir2/web/util/NarrativeUtils.java
- omod/src/main/resources/config.xml
- omod/src/test/java/org/openmrs/module/fhir2/web/util/NarrativeUtilTest.java
Added support for overriding default narratives, with the narrative override property file location to be stored as the global property `narrativesOverridePropertyFile`.
see https://issues.openmrs.org/browse/FM2-251
> FM2-251: Add support for overriding default narratives

- omod/src/main/java/org/openmrs/module/fhir2/narrative/OpenMRSNarrativeTemplate.java
- omod/src/main/java/org/openmrs/module/fhir2/narrative/OpenMRSNarrativeTemplateManifest.java
- omod/src/main/java/org/openmrs/module/fhir2/narrative/OpenMRSThymeleafNarrativeGenerator.java
- omod/src/main/java/org/openmrs/module/fhir2/web/servlet/FhirRestServlet.java
- omod/src/main/java/org/openmrs/module/fhir2/web/util/NarrativeUtils.java
- omod/src/test/java/org/openmrs/module/fhir2/narrative/BaseFhirNarrativeTest.java
- omod/src/test/java/org/openmrs/module/fhir2/narrative/NarrativeGeneratorTest.java
- omod/src/test/java/org/openmrs/module/fhir2/web/util/NarrativeUtilTest.java
- omod/src/test/resources/org/openmrs/module/fhir2/narrative/testNarrative.html
- omod/src/test/resources/org/openmrs/module/fhir2/narrative/testNarratives.properties
- omod/src/test/resources/org/openmrs/module/fhir2/narrative/testNarrativesWithInvalidProperty.properties
Added support for relative paths prefixed with `openmrs:` for location of narratives and properties file. 
For example, the relative path `openmrs:configuration/Patient.html` would point to the location `<OPENMRS_APPLICATION_DATA_DIRECTORY>/configuration/Patient.html`.
see https://issues.openmrs.org/browse/FM2-252
> FM2-252: Add support for relative path with prefix 'openmrs:' for narrative templates

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirEncounterService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseEncounterDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryInclude.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/EncounterSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEncounterServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderTest.java
- api/src/test/resources/log4j.xml
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/EncounterFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderWebTest.java
Both FM2-477 and FM2-478 are written with a common goal - to be able to return encounters (only encounters, not visits) that contain medication requests.  Those 2 tickets break this down into supporting the _has:MedicationRequest:encounter parameter on the Encounter resource (FM2-477), and in supporting the _tag=http://fhir.openmrs.org/ext/encounter-tag|encounter on the Encounter resource.
See:  https://issues.openmrs.org/browse/FM2-477
See:  https://issues.openmrs.org/browse/FM2-478
Both of these tickets hit the same blocks of code, and both benefited from some refactoring I did as a part of this on the FhirEncounterService and associated unit tests, so I bundled these together so as not to have to deal with a mess of merge issues.
> FM2-477 and FM2-478: Support limiting to only Encounters that have medication requests

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseReferenceHandlingTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ConceptTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEncounterDaoImplTest.java
Populates the "display" property on the Medication Reference, and the "text" property on the Codeable Concept reference, to better enable direct usage of these properties without requiring additional requests.
> Add additional display text to concept and medication resources

- api/src/main/java/org/openmrs/module/fhir2/api/FhirPersonService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirPersonServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/PersonSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/PersonFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/PersonFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirPersonServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/PersonFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/PersonFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/PersonFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/PersonFhirResourceProviderWebTest.java
- Added PersonSearchParams class that extends the BaseResourceSearchParams.
- Refactor all provider classes (r3 and r4).
- Ensure all tests are passing
> FM2-481: Clean up parameter passing in Person Service class search method

- api/src/main/java/org/openmrs/module/fhir2/providers/r4/MedicationDispenseFhirResourceProvider.java
- integration-tests-2.6/src/test/java/org/openmrs/module/fhir2/provider/r4/MedicationDispenseFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/MedicationDispense_json_merge_patch.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/MedicationDispense_json_patch.json
Ensure the MedicationDispense Resource Provider(R4) can support JSON_MERGE_PATCH and JSON_PATCH patch operations.
see https://issues.openmrs.org/browse/FM2-587
> FM2-587: Add Support for JSON patching operations — MedicationDispense Resource

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/AllergyIntoleranceFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/AllergyIntolerance_xmlpatch.xml
This pull request introduces integration tests for the [XML PATCHing](https://www.rfc-editor.org/rfc/rfc7351) operations on the Allergy Intolerance Resource.
```
<replace sel="/fhir:AllergyIntolerance/fhir:category/@value">
food
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-595
No? …
> FM2-595: Add support for XML patching operations - AllergyIntolerance Resource

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/PersonFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Person_xmlpatch.xml
This ticket introduces integration tests for [XML PATCH](https://www.rfc-editor.org/rfc/rfc7351) operations on the Person Resource.
```
<replace sel="/fhir:Person/fhir:gender/@value">
female
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-594
No? -> figure out why and add the fix to …
> FM2-594: Add support for XML patching operations - Person Resource

- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/EncounterFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Encounter_xml_patch.xml
This ticket introduces [XML PATCH](https://www.rfc-editor.org/rfc/rfc7351) operations on the Encounter Resource.
For example the following xml doc should be supported:
```
<replace sel="/fhir:Encounter/fhir:period/fhir:start/@value">                  
2005-02-01T00:00:00+05:30       
</replace>
</diff>
```
see https://issues.openmrs.org/browse/FM2-602
No? …
> FM2-602: Add support for XML PATCHing operations - Encounter Resource

- api/src/main/java/org/openmrs/module/fhir2/api/FhirDiagnosticReportService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/SearchQueryInclude.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/DiagnosticReportSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirDiagnosticReportServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProviderTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/DiagnosticReportFhirResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/DiagnosticReportFhirResourceProviderWebTest.java
> FM2-481: Clean up parameter passing for DiagnosticReport Service Search

- api-2.2/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2.java
- api-2.2/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl_2_2Test.java
- api/src/main/java/org/openmrs/module/fhir2/api/FhirConditionService.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/ConditionSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/ConditionFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/ConditionFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirConditionServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/ConditionFhirR3ResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/ConditionFhirResourceProviderTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/ConditionFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/ConditionFhirResourceProviderIntegrationTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r3/ConditionFhirR3ResourceProviderWebTest.java
- omod/src/test/java/org/openmrs/module/fhir2/providers/r4/ConditionFhirResourceProviderWebTest.java
> FM2-481: Clean up parameter passing for Condition Service Search

- api/src/main/java/org/openmrs/module/fhir2/api/FhirContactPointMapService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirContactPointMapDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirContactPointMapDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirContactPointMapServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirImmunizationServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TelecomTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/util/GeneralUtils.java
- api/src/main/java/org/openmrs/module/fhir2/model/FhirContactPointMap.java
- api/src/main/resources/liquibase.xml
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirContactPointMapDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirContactPointMapServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TelecomTranslatorImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/ImmunizationFhirResourceProviderIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/api/dao/impl/FhirContactPointMapDaoImplTest_initial_data.xml
Add support for Fhir ContactPoint's `system`, `use` and `rank` in openmrs model.
see https://issues.openmrs.org/browse/FM2-606
> FM2-606: Mapping ContactPoints to OpenMRS

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/DosageTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/DosageTranslatorImplTest.java
see https://issues.openmrs.org/browse/FM2-632
> FM2-632: Medication Request should return Null when Drug Order has dose units but no dose

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PersonNameTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PersonNameTranslatorImplTest.java
HumanName.text is now set to the `Person.getFullName()` value, which uses the default name template.
see https://issues.openmrs.org/browse/FM2-631
> FM2-631: HumanName.text should use the NameTemplate

- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ValueSetTranslatorImplTest.java
Added a mock of `ConceptMapType` in `ValueSetTranslatorImplTest` to resolve an issue where the `conceptMap` object was looking for `defaultConceptMapType` without it.
see https://issues.openmrs.org/browse/FM2-635
> FM2-635: ValueSetTranslatorImplTest unit test failure fix

- api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/search/param/TaskSearchParams.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ServiceRequestTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/model/FhirTask.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProvider.java
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirTaskServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/search/TaskSearchQueryTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/TaskTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceProviderTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/TaskFhirResourceIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/TaskFhirResourceIntegrationTest.java
- test-data/src/main/resources/org/openmrs/module/fhir2/api/dao/impl/FhirMedicationRequestDaoImpl_initial_data.xml
- test-data/src/main/resources/org/openmrs/module/fhir2/api/dao/impl/FhirTaskDaoImplTest_initial_data.xml
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Task_create.json
- test-data/src/main/resources/org/openmrs/module/fhir2/providers/Task_create.xml
Made below Changes to FHIR Task Entity Model:
- Added new columns to `fhir_task`:
- `task_code`: to determine task type
- `execution_start_time`: start time of execution
- `execution_end_time`: end time of execution
- `comment`: comment to task
- Added a new table `fhir_part_of_reference` to support subtasks to a parent task.
see https://issues.openmrs.org/browse/FM2-636
talk thread ref https://talk.openmrs.org/t/contribution-to-fhir-task/42015
> FM2-636: Enhancements in Existing FHIR Task Resource

- .github/workflows/main.yml
https://openmrs.atlassian.net/browse/O3-3560
Most of our repositories currently use actions/upload-artifact@v3 for artifact uploading and actions/download-artifact@v3 for artifact downloading within our CI pipelines. However, an updated version, actions/upload-artifact@v4 and actions/download-artifact@v4, is now available and should be considered for adoption across our projects.
> (chore) O3-3560: Use latest Actions in GH Actions

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterParticipantTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterParticipantTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EncounterTranslatorImplTest.java
This PR resolves the SQLIntegrityConstraintViolationException when creating an encounter via the FHIR API with a participant. The root cause was the EncounterProvider entity being flushed to the database before the Encounter was created, resulting in a null encounter_id. This update ensures the EncounterProvider entity is properly linked to the Encounter before being persisted.
see https://issues.openmrs.org/browse/FM2-639 …
> (fix) Set encounter and default role for encounter provider entity

- api/src/main/java/org/openmrs/module/fhir2/api/FhirEpisodeOfCareService.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/FhirEpisodeOfCareDao.java
- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/FhirEpisodeOfCareDaoImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/impl/FhirEpisodeOfCareServiceImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/EpisodeOfCareTranslator.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/EpisodeOfCareTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r3/EpisodeOfCareFhirResourceProvider.java
- api/src/main/java/org/openmrs/module/fhir2/providers/r4/EpisodeOfCareFhirResourceProvider.java
- api/src/test/java/org/openmrs/module/fhir2/api/dao/impl/FhirEpisodeOfCareDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/impl/FhirEpisodeOfCareServiceImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/EpisodeOfCareTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r3/EpisodeOfCareFhirResourceProviderTest.java
- api/src/test/java/org/openmrs/module/fhir2/providers/r4/EpisodeOfCareFhirResourceProviderTest.java
- omod/src/main/resources/org/openmrs/module/fhir2/narratives.properties
- omod/src/main/resources/org/openmrs/module/fhir2/narratives/EpisodeOfCare.html
- test-data/src/main/resources/org/openmrs/module/fhir2/api/dao/impl/FhirEpisodeOfCareDaoImpl_2_2Test_initial_data.xml
Added support for fhir EpisodeOfCare with a mapping from the openmrs PatientProgram. This is a one-way mapping from the openmrs PatientProgram to EpisodeOfCare and doesn't include support for deleting / creating / updating.
see https://issues.openmrs.org/browse/FM2-608
No? Unsure? -> …
> FM2-608: Add EpisodeOfCare FHIR2 Module with Mapping of Patient Program

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/BaseReferenceHandlingTranslator.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/BaseReferenceHandlingTranslatorTest.java
see https://issues.openmrs.org/browse/FM2-645
> FM2-645: Remove identifier from Practitioner display field

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/PatientTranslatorImplTest.java
When updating a patient's name using the FHIR endpoint, a new person_name entry is created in the database instead of voiding the existing one and creating a new entry. This results in multiple active names for a single patient, which is incorrect and leads to data inconsistencies. Additionally, OpenMRS does not consider more than one name and always picks the first one, so users cannot see any changes in the **UI.**
This fix addresses the problem by:
- Replacing the current name with the new entry, matching their ids (which is how the rest API currently works).
If the person's name doesn't contain an ` id`for some reason (in a normal case it will), it will “ replace ” the preferred name for the person.
By implementing this approach, we ensure the UI reflects the latest changes …
> FM2-650: Replace the existing name instead of creating a new name

- api/src/main/java/org/openmrs/module/fhir2/api/dao/impl/BaseFhirDao.java
- omod/src/main/java/org/openmrs/module/fhir2/web/servlet/FhirRestServlet.java
- omod/src/test/java/org/openmrs/module/fhir2/web/servlet/FhirRestServletTest.java
see https://openmrs.atlassian.net/browse/FM2-651
> FM2-651: Allow DAOs access to all API load-able by the OpenMRS Class loader.

- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImpl.java
- api/src/main/java/org/openmrs/module/fhir2/api/translators/impl/ObservationValueTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhir2/MockedGlobalPropertyServiceConfiguration.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationReferenceRangeTranslatorImplTest.java
- api/src/test/java/org/openmrs/module/fhir2/api/translators/impl/ObservationValueTranslatorImplTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r3/ObservationFhirResourceProviderIntegrationTest.java
- integration-tests/src/test/java/org/openmrs/module/fhir2/providers/r4/ObservationFhirResourceProviderIntegrationTest.java
OpenMRS numeric obs store their values a double-precision floating point numbers, which allows values with a decimal and those without one. We also have metadata on the concept indicating whether the numbers after the decimal should be retained or not. Previously, when displaying obs values, we were ignoring this distinction and always returning a double-precision floating point value which was treated as having at least one significant decimal point.
This PR fixes that so that for concepts that are marked as not supporting decimals are treated as integer values.
see https://issues.openmrs.org/browse/FM2-656 …
> FM2-656: If the concept does not allow decimals, only use integers
